spring:
  application:
    name: websocket
  port: 9999
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/eigdb
    username: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none