spring:
  application:
    name: websocket
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/eigdb
    username: root
    password: eig7582!
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
server:
  port: 9999

---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: devel

server:
  port: 9988

